### ISSUE TITLE
Problems expanding zip archives

### ISSUE THREAD

**Issue by cbmtrx** [publicsamples/Yamaha-CS30L#1]
Don't know if this is an isolated case, but several—many, in fact—of the large multi-Gb audio archives associated with these Modular samples archives downloaded from Dropbox are not unzipping on Mac OS. I'm on 10.12.6.

Figured you might like to know in case there was a problem with those archives.

**Comment by RickTaylor79** [comment]
Thanks for letting me know.  I'm currently in a place with limited wi-fi so can't do much to test them at the moment. 

What program are you using to extract the zips? Does It give you a specific error message? The built in Archive Utility can be a bit temperamental with large zips created on other OSes (The zip files are generated on Dropbox's end when you click on the download link)  

You could try using an alternative extraction tool (Keka, The Unarchiver), or try from the terminal:

`unzip path/to/YamahaCS30L.zip`

If that doesn't work you could signup for a dropbox account and use the "Save to Dropbox" button. This will sync the files to your account, this way you don't need to extract anything. They offer a 30 day free trial which should be enough time to grab everything you want :)

Let me know how you get on!

**Comment by cbmtrx** [comment]
Actually you hit the nail on the head! The archives were too large for the
Archive Utility app so I tried the Unarchiver—worked like a charm.

Thanks.

**Comment by RickTaylor79** [comment]
Thanks for the update!

I'll update the docs for the larger libraries when time permits. Closing this for now, but if you have any other problems let me know.
